services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - frontend-net
networks:
  frontend-net: